#!/bin/zsh

if [ x"$HOME" = x ] ; then
        export HOME=$(cd ~ ; pwd)
fi

if [ x"$HOSTNAME" = x ] ; then
        export HOSTNAME=$(hostname)
fi

export MANWIDTH=80
export EDITOR=vim

export RLWRAP_HOME=~/.cache/rlwrap/

export LC_MESSAGES=C
export LC_ALL=C

# detect chroot
[[ `stat -c %i /` -ne 2 ]] && export CHROOT=yes

# path junk

if [ $UID -eq 0 ]; then
        PATH=~root/bin:$PATH
else
        path=(${HOME}/.bin:${HOME}/.local/bin:${HOME}/development/go/bin  $path)
fi

path=($path /bin:/usr/bin /usr/local/bin /sbin:/usr/sbin /usr/local/sbin /usr/games)

# zsh functions
fpath=($HOME/.zsh/func $fpath)

# less options
LESS=RSX
# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# this makes man pages look nicer...
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;37m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'


export PAGER=less
export VPAGER="vim -R -"

# <dave0> if you use this bash function, you can do 'dpan DBD::ODBC'
#         and it will get the debian package if it exists
# <blastmaster> Its just a shortcut to install perl packages using the
# perl package notation.
function dpan () {
    PKG=$(perl -e '$_=lc($ARGV[0]); s/::/-/g; print "lib$_-perl\n"' $1)
    echo apt-get install $PKG
}

# print pretty calendars
alias pcal-portrait="pcal -F 1 -m -J -p"
alias pcal-landscape="pcal -F 1 -m -J -l"
