#! /usr/bin/zsh

# activate or deactivate a given virtual env

virtenv()
{
    emulate -L zsh
    local cmd=${1:?"no cmd given use activate or deactivate"}
    local venv=${2:?"no virtual env given"}
    if [[ "${cmd}" == "activate" ]]; then
        source ${HOME}/virtenv/$venv/bin/activate
    elif [[ "${cmd}" ==  "deactivate" ]]; then
        deactivate
    else
        echo "invalid command $cmd"
    fi
}
