#!/bin/sh
#
# Public domain
    #up_fgcolor = "#D00003", down_fgcolor = "#95D043",
# Author: roman [] tsisyk.com
#
# Usage: ./me url [youtube-dl parameters]
#

COOKIE_FILE=/tmp/youtube-dl-cookies.txt
mpv -cache 9999 -cookies -cookies-file ${COOKIE_FILE} $(youtube-dl -g --cookies ${COOKIE_FILE} $*)
